Afd 74 landing page view
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #17
Opened 2021-09-30 15:10 UTC by TheGuardingDark

Migrated files into React structure. Set-up React Router and error boundary. Built styling for Nav, Footer, and Landing Page with breakpoints.

Need to add sprint1 file to gitignore for future pushes

2021-09-30 15:38 UTC, aperezsantos submitted a review, later dismissed
Things are looking great. Love how well you use mixins!

2021-09-30 18:16 UTC, scullenDev requested changes
Requesting a few optimizations per the comments...

2021-09-30 18:16 UTC, scullenDev commented on src/App.jsx
> +          <Route exact path="/">
Since you're not passing props into any of the Routed components, consider streamlining using this format:

`<Route path="/path/here" component={ComponentNameHere} />`

Both ways are correct and technically the way you did it is more flexible, but streamlining using the technique above rather than nesting will increase the readability of the App.jsx overall.

2021-09-30 18:16 UTC, scullenDev commented on src/App.jsx
> +    <Router>
In order to get your Navbar to work in your Error Boundary, you'll need to move the <Router> wrapped from App.jsx to the index.jsx wrapped around <ErrorBoundary> as otherwise you can't use <Link>s and <NavLink>s.

2021-09-30 18:16 UTC, scullenDev commented on src/components/Button.jsx
> +const Button = ({ text }) => {
Yaaaay for modularization!

2021-09-30 18:16 UTC, scullenDev commented on src/components/Button.jsx
> +const Button = ({ text }) => {
To make it more flexible, you could add an optional 'type' prop that defaults to "button" so that you could use it to generate submit and reset buttons, too.

2021-09-30 18:16 UTC, scullenDev commented on src/index.jsx
> +  <ErrorBoundary>
See comment above re: <Router> and where and why to wrap it.

2021-09-30 18:16 UTC, scullenDev commented on src/pages/Bookshelf.jsx
> +        <button type="button">Book Details</button>
Be sure to switch this out later to use your magical <Button> component! (Don't worry about it for now, though.)

2021-09-30 18:16 UTC, scullenDev commented on src/sprint1/assets/js/index.js
> +
Guessing you'll be replicating this functionality the React way during this sprint.

2021-09-30 22:35 UTC, scullenDev requested changes
Small change requested re: Error Boundary.

2021-09-30 22:35 UTC, scullenDev commented on src/ErrorBoundary.jsx
> +    state = { hasError: false};
Looks like you're renaming your state key/val pair here from 'error' to 'hasError'. Make sure to be consistent, as line 11 and 19 are both expecting the value to be called 'error.'

2021-09-30 22:35 UTC, scullenDev commented on src/components/Button.jsx
> +Button.defaultProps = {
Does this seem to work okay to plug in the default type when not provided? If not you could use `const Button = ({ text, type = "button" }) => {}` instead. But then again you'll eventually be adding propTypes and defaultProps everywhere so hopefully it works this way for you.

2021-09-30 22:35 UTC, scullenDev commented on src/index.jsx
> +  <Router>
Exactly!

2021-09-30 23:00 UTC, TheGuardingDark commented on src/components/Button.jsx
> +Button.defaultProps = {
It works so far, but I'll keep an eye on it

2021-09-30 23:01 UTC, TheGuardingDark commented on src/ErrorBoundary.jsx
> +    state = { hasError: false};
Fixed!

2021-10-01 14:07 UTC, aperezsantos commented on src/styles/_mixins.scss
> +// STARS
I'm sure this is here for organization, I just want to point it out for later.

2021-10-01 14:07 UTC, aperezsantos approved these changes
Wonderful work! Clean and organized!

2021-10-01 15:24 UTC, scullenDev approved these changes
Looks good, but see note re: Error Boundary.

2021-10-01 15:24 UTC, scullenDev commented on src/ErrorBoundary.jsx
> +                <div className='error'>
Hey Liv, this is fine. It looks like you simplified the Error Boundary's return so that it no longer includes your Navbar/Footer. That means you no longer need the Router wrapper wrapped around this element in order for the Error Boundary to work, but I think it's still good to keep it that way in case you beef up your Error Boundary contents later.

2021-10-01 15:28 UTC, merged