AFD 82 Add Book View
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #19
Opened 2021-10-07 00:39 UTC by TheGuardingDark

Converted Add Book View to React components. Added additional styling and breakpoints
No form functionality at this stage of development

2021-10-07 15:24 UTC, aperezsantos commented on src/pages/AddBook.jsx
> +// import BookCard from '../components/BookCard';
I'm assuming this is here because it will be used in the future?

2021-10-07 15:26 UTC, aperezsantos commented on src/styles/_mixins.scss
>  // STARS
Just a reminder to remove this later on

2021-10-07 15:28 UTC, katieburrows submitted a review, later dismissed
Based off of my two comments and what the aim of the page is at this point I have approved this request.  Those comments will be addressed later when you add more functionality/"wire it up."

2021-10-07 15:28 UTC, katieburrows commented on src/components/BookForm.jsx
> +      <CustomPub />
There is an errant border on the left-hand side of the drop-down menu.  I am able to interact with (type into) all of the form fields on the add book page except for the published field.

2021-10-07 15:28 UTC, katieburrows commented on src/components/BookForm.jsx
> +        className="form__text form__pages form__mobile form__text--pages"
I am able to enter text into this field; however, the ascending/descending buttons do not work.

2021-10-07 15:29 UTC, aperezsantos submitted a review, later dismissed
¡Buen trabajo! Great job! I left a few comments, mainly reminders about minor comments in the code that could be removed at a later time.

2021-10-07 15:38 UTC, TheGuardingDark commented on src/components/BookForm.jsx
> +      <CustomPub />
This will be addressed in a different ticket

2021-10-07 15:38 UTC, TheGuardingDark commented on src/components/BookForm.jsx
> +        className="form__text form__pages form__mobile form__text--pages"
This will be addressed in a different ticket

2021-10-07 16:50 UTC, grobertsTechtonic requested changes
Your add book page looks great, especially on mobile views.  Just a few minor-ish changes and then it should be good to go 👍🏻

2021-10-07 16:50 UTC, grobertsTechtonic commented on package.json
> +    "npm": "^7.24.2",
I don't think you need this dependency in your project.  It's important to remove unused packages to reduce node_package bloat.  If you are using this, please let me know as I would be interested to know more about the use case.

2021-10-07 16:50 UTC, grobertsTechtonic commented on src/components/CustomPub.jsx
> +      <TiArrowSortedDown className="form__selectPub--arrow" />
The position of this icon trends to the right and overflows its container boundary on screens >= 1300px

2021-10-07 16:50 UTC, grobertsTechtonic commented on src/styles/_footer.scss
>  }
There are a couple of breakpoints where the footer does not span the width of the page.  You could remedy this by adjusting the width of the footer or by adjusting the width of the main content on the add book page.

2021-10-07 16:50 UTC, grobertsTechtonic commented on src/styles/_form.scss
> +            }
A more common way of doing large inputs like this is to align the input text across the top of the input area instead of the middle.  Not a requirement at all though.

2021-10-07 16:50 UTC, grobertsTechtonic commented on src/styles/_form.scss
> +            }
Your synopsis input text also does not break when it hits the length of the input container.  You should remedy this, as it makes for a difficult user experience with editing the synopsis.

2021-10-07 19:33 UTC, TheGuardingDark commented on src/styles/_footer.scss
>  }
I've adjusted the width of the footer and added a bit of padding to keep it center.

2021-10-07 20:14 UTC, TheGuardingDark commented on src/styles/_form.scss
> +            }
Changed the synopsis input into a text area to align toward the top and word-wrap.

2021-10-07 22:25 UTC, TheGuardingDark commented on src/components/CustomPub.jsx
> +      <TiArrowSortedDown className="form__selectPub--arrow" />
I've adjusted the wrapper settings and added a few more breakpoints.

2021-10-08 16:34 UTC, grobertsTechtonic approved these changes
💯

2021-10-08 17:13 UTC, aperezsantos approved these changes
Things are spaced out well, the changes you made are perfect, and your code looks clean.

2021-10-08 17:14 UTC, merged