Afd 90 edit book view
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #21
Opened 2021-10-15 21:43 UTC by TheGuardingDark

Finished styling for all pages with breakpoints and began working on mobile menu.

Known issues: 
mobile menu doesn't close when rendering new page. hamburger gets stuck in 'open position.

blank space between content and footer at smaller desktop sizes, almost always at 769px

2021-10-16 00:04 UTC, katieburrows submitted a review, later dismissed
I love the hamburger menu animation!  On my system it looks like the block is moving too far up and to the left and then re-centers in a glitchy kind of way.  It starts out smooth then gets a little glitchy.  I'm also noticing extra space on the right-hand side of the navbar when I'm at 480px.

2021-10-25 17:45 UTC, scullenDev requested changes
Requesting minor changes.

Is there still code you want me to look at re: the hamburger menu? If so, please send me a branch name to work off of and a link to the documentation for the package you used.

2021-10-25 17:45 UTC, scullenDev commented on src/components/BookForm.jsx
> +      <label
To placate your linter, you'll have to both wrap the labels AROUND their respective inputs **and** still associate the label with the input via the `httpFor` attribute. Let me know if you have related questions.

2021-10-25 17:45 UTC, scullenDev commented on src/components/Button.jsx
>  Button.defaultProps = {
Thank you for doing your propTypes/defaultProps up front... yay!

2021-10-25 17:45 UTC, scullenDev commented on src/components/CustomPub.jsx
> +        <option value="0">{date}</option>
I like to believe that all books under the sun were published on one of these four dates.

2021-10-25 19:43 UTC, TheGuardingDark commented on src/components/CustomPub.jsx
> +        <option value="0">{date}</option>
They were, Sarah. They were. But yeah that'll change once the edit form is wired up

2021-10-26 15:00 UTC, scullenDev approved these changes
Looks good!

2021-10-26 15:56 UTC, aperezsantos approved these changes
Beyond the known issues and some of the commented code, which I assume are things you're going to work on, I think everything looks great.

2021-10-26 15:58 UTC, merged