Afd 98 bookshelf logic
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #22
Opened 2021-10-26 16:57 UTC by TheGuardingDark

This encompasses both the Bookshelf Logic and Search Bar Logic. I accidentally began the add book logic on this branch so there are a few things, specifically in the form file that are not operational.

known issues: Add/Edit pages will break application at this time

2021-10-26 18:12 UTC, aperezsantos reviewed
Unsure how important it is, but I noticed that the search bar/button look different from desktop to mobile view.

2021-10-26 18:12 UTC, aperezsantos commented on src/pages/Bookshelf.jsx
>  import BookCard from '../components/BookCard';
Going off of the jira ticket, I'm currently not seeing any pre-loaded Book cards, both in the mobile view and desktop view.

2021-10-26 18:18 UTC, aperezsantos submitted a review, later dismissed
Based on your PR comment, I think you know some changes you'll need to make. Other than that, I would suggest loading some book-cards to the bookshelf, and looking into the differences between the mobile and desktop versions of your search field.

2021-10-26 19:13 UTC, TheGuardingDark commented on src/pages/Bookshelf.jsx
>  import BookCard from '../components/BookCard';
Do you mean that you aren't seeing any books on the bookshelf page?

2021-10-26 19:14 UTC, TheGuardingDark commented on src/pages/Bookshelf.jsx
>  import BookCard from '../components/BookCard';
What exactly do you mean by the search bar being different? Do you mean the magnifying glass for mobile?

2021-10-26 19:17 UTC, TheGuardingDark commented on src/pages/Bookshelf.jsx
>  import BookCard from '../components/BookCard';
Did you start the json server? All the books are in the json db. You'll need to start that in order to see anything load

2021-10-27 16:46 UTC, TheGuardingDark commented on src/components/BookForm.jsx
>        <label htmlFor="title" className="form__label">
the changes I made to the labels got replaced when I messed up the branches. They are back to what they were in the ticket I'm currently working on

2021-10-27 17:03 UTC, aperezsantos commented on src/styles/_card.scss
> +        // text-decoration: none;
Is this something you want to utilize later?

2021-10-27 17:05 UTC, aperezsantos commented on src/pages/Details.jsx
> +      <h1 className=" details__text details__text--title">{book.title}</h1>
I noticed your spacing between curly braces changes from having space in the beginning and end, to no spacing. Is this done purposely?

2021-10-27 17:11 UTC, aperezsantos submitted a review, later dismissed
Things are looking well!
I know we talked about it yesterday, but just a reminder that when going from desktop to mobile device, the nav bar becomes shorter than the width of the page. This creates white space between on the right side. The footer does not have the same effect.

2021-10-27 17:28 UTC, scullenDev requested changes
Requesting a few small changes. Please let me know if you have any questions!

2021-10-27 17:28 UTC, scullenDev commented on src/components/BookForm.jsx
>        <label htmlFor="title" className="form__label">
Perfect, thanks for clarifying!

2021-10-27 17:28 UTC, scullenDev commented on src/pages/Bookshelf.jsx
> +        // how do I make eslint happy??
ESLint is determined to be emo.

2021-10-27 17:28 UTC, scullenDev commented on src/pages/Bookshelf.jsx
> +  searchTerm: {},
I would recommend changing the searchTerm default to '' and the setSearchTerm default to maybe an empty arrow function, just to stick with the specified types.

2021-10-27 17:28 UTC, scullenDev commented on src/pages/Details.jsx
> +  const [book, setBook] = useState({});
Please destructure the `book` object so that you can reduce the use of dot notation in the JSX below. (ie `title` instead of `book.title`)

2021-10-27 17:28 UTC, scullenDev commented on src/pages/Details.jsx
> +        <Link to={`/editBook:${id}`}>
Guessing this 'to' prop should instead be `/editBook/${id}`? (removed the colon character and added a slash between the url parts)

2021-10-27 17:28 UTC, scullenDev commented on src/pages/Details.jsx
> +        <Link to={`/editBook:${id}`}>
Let me know if you need any further clarification or if I'm missing something.

2021-10-27 17:28 UTC, scullenDev commented on src/utils/API.js
> +  return axios.get('http://localhost:3000/books');
Please create a variable for the base url ('http://localhost:3000/books') to make your code DRYer. (Unless this is addressed in the current branch you're working on, then don't worry about it.)

2021-10-27 17:37 UTC, TheGuardingDark commented on src/styles/_card.scss
> +        // text-decoration: none;
nope I'll remove it

2021-10-27 17:41 UTC, TheGuardingDark commented on src/pages/Details.jsx
> +      <h1 className=" details__text details__text--title">{book.title}</h1>
Usually I'll use spaces when passing in props to the component and then no spaces for local variables

2021-10-27 23:41 UTC, scullenDev approved these changes
Looks great, sorry for the delay!

2021-10-28 14:09 UTC, merged