Afd 110 edit book logic
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #25
Opened 2021-11-08 00:40 UTC by TheGuardingDark

Edit Book page allows you to edit the book details. You can reset the form to the original details. Submitting will take you to the bookshelf.

2021-11-08 22:06 UTC, aperezsantos submitted a review, later dismissed
So far, everything functions as expected, except for the mentioned edit image feature (line 26). Glad you made a note of it in your code. It helped me recognize that as something you're still working on.

I would also take a look at your footer. Moving b/w desktop and mobile view, shortens its width for me. I believe it has to do with the EditBook.grid component.

Also between about 480 and and 765 (width), the bottom two buttons disappear behind the footer.

2021-11-09 02:01 UTC, scullenDev requested changes
A few recommendations/comments... great work though, Liv.

2021-11-09 02:01 UTC, scullenDev commented on src/components/BookForm.jsx
> +  const titleRef = document.getElementById('title');
Curious if you had issues w/the original implementation of useRef here?

2021-11-09 02:01 UTC, scullenDev commented on src/components/BookForm.jsx
> +    if (id) {
I love that resetting repopulates the book info in Edit View!

2021-11-09 02:01 UTC, scullenDev commented on src/components/BookForm.jsx
>    const [formObj, setFormObj] = useState({
I'm recommend storing the formObj defaults in a variable (preferably within this file but ABOVE the component) so you don't need to duplicate them here and in the reset.

2021-11-09 02:01 UTC, scullenDev commented on src/components/Stars.jsx
> +      getBook(id)
Would it be feasible to pass this book.rating value in from the parent component(s)? It's not ideal that you're making HTTP calls from the Stars component and whatever parent component it resides in (Details, Edit, etc). Please see if a refactor is possible to refactor.

2021-11-09 16:02 UTC, TheGuardingDark commented on src/components/BookForm.jsx
> +  const titleRef = document.getElementById('title');
I actually forgot to change it back. I have now and it seems to be working.

2021-11-09 16:02 UTC, TheGuardingDark commented on src/components/Stars.jsx
> +      getBook(id)
You got it

2021-11-09 16:58 UTC, scullenDev approved these changes
Nice work, Liv!

2021-11-09 17:05 UTC, merged