Afd 124 set up routes
TechtonicAcademy/fluidity-library-project-TheGuardingDark pull request #29
Opened 2021-11-12 15:49 UTC by TheGuardingDark

Creates routes and controllers for book and author.

Post, Put, Get, Delete routes are working as expected when navigating to them through Postman

2021-11-13 00:46 UTC, scullenDev requested changes
Requesting a few small changes, mostly re: formatting. (You may want to set up a set of generic linter rules to run globally to catch such issues going forward.

2021-11-13 00:46 UTC, scullenDev commented on server/controllers/bookController.js
> +const { Op } = require("sequelize");
Make sure to run your linter/correct any inconsistencies, like the double quotes used on the import here.

2021-11-13 00:46 UTC, scullenDev commented on server/controllers/bookController.js
> +const { Author, Book, Sequelize } = require('../models');
As far as I can see, you're not using the import `Sequelize` here? If not, please remove.

2021-11-13 00:46 UTC, scullenDev commented on server/controllers/bookController.js
> +                firstName: firstName,
I'd recommend streamlining these key/val pairs as in the lines above and here, the keys are identical to the values.

2021-11-13 00:46 UTC, scullenDev commented on server/controllers/bookController.js
> +
It also looks like you might be using four spaces rather than 2? Please use the same spacing/tab convention from the Airbnb style guide.

2021-11-13 00:46 UTC, scullenDev commented on server/controllers/bookController.js
> +            .catch((err) => res.status(422).json);
Looks like you're missing the end of this line... guessing it should be `.catch((err) => res.status(422).json(err)` instead?

2021-11-13 00:46 UTC, scullenDev commented on server/models/book.js
> -module.exports = function (sequelize, DataTypes) {
Same here re: four spaces vs the expected two.

2021-11-13 22:37 UTC, TheGuardingDark commented on server/controllers/bookController.js
> +const { Op } = require("sequelize");
Sometimes the linter catches this and sometimes it doesn't. Is there a way to make it stricter or do I need to install another plugin?

2021-11-13 22:37 UTC, TheGuardingDark commented on server/controllers/bookController.js
> +
So my eslintrc file already has tabWidth set to 2, is there somewhere else I need to specify
that or am I supposed to be doing it manually?

2021-11-15 15:29 UTC, scullenDev approved these changes
Looks good; we can address any general back-end formatting issues in a later ticket.

btw that the SonarCloud issue is not on your end... I hope to get things fixed with that service later today.

2021-11-15 15:29 UTC, scullenDev commented on server/controllers/bookController.js
> +
I think this is fine for now, and we can correct any formatting issues on a later ticket. Look into doing an auto-format on save on VSCode, and make sure your VSCode is set to use two spaces for indentation, etc. We may need to dig into the VSCode settings at some point to get everything in place.

2021-11-15 15:30 UTC, merged